### ISSUE TITLE
incompatible with i386 ?

### ISSUE THREAD

**Issue by tonyshaoxu** [puxxustc/muon#13]
/usr/bin/ld: i386:x86-64 architecture of input file `tutorial/step8.o' is incompatible with i386 output
/usr/bin/ld: tutorial/step8.o: file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [tutorial/step8] Error 1

**Comment by puxxustc** [comment]
Please provide full compile log.

**Comment by tonyshaoxu** [comment]
When I tried to build libmill with command make, please see the log below.
user@ubuntu:~/Downloads/muon/source/muon/libmill$ ./autogen.sh 
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autoreconf: configure.ac: tracing
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in `.'.
libtoolize: copying file `./ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force
autoreconf: configure.ac: not using Autoheader
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
user@ubuntu:~/Downloads/muon/source/muon/libmill$ ./configure --enable-shared=false
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for gawk... (cached) gawk
configure: Mill package version: Unknown
configure: Mill ABI version: 19.1.1
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for gcc option to accept ISO C99... -std=gnu99
checking for posix_memalign... yes
checking for mprotect... yes
checking for clock_gettime in -lrt... yes
checking for clock_gettime... yes
checking for socket in -lsocket... no
checking for epoll_create... yes
checking for kqueue... no
checking how to print strings... printf
checking for a sed that does not truncate output... (cached) /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc -std=gnu99... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert i686-pc-linux-gnu file names to i686-pc-linux-gnu format... func_convert_file_noop
checking how to convert i686-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc -std=gnu99 object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -std=gnu99 -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc -std=gnu99 supports -fno-rtti -fno-exceptions... no
checking for gcc -std=gnu99 option to produce PIC... -fPIC -DPIC
checking if gcc -std=gnu99 PIC flag -fPIC -DPIC works... yes
checking if gcc -std=gnu99 static flag -static works... yes
checking if gcc -std=gnu99 supports -c -o file.o... yes
checking if gcc -std=gnu99 supports -c -o file.o... (cached) yes
checking whether the gcc -std=gnu99 linker (/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libmill.pc
config.status: executing depfiles commands
config.status: executing libtool commands
user@ubuntu:~/Downloads/muon/source/muon/libmill$ make
  CC       libmill_la-chan.lo
  CC       libmill_la-cr.lo
  CC       libmill_la-debug.lo
  CC       libmill_la-ip.lo
  CC       libmill_la-list.lo
  CC       libmill_la-mfork.lo
  CC       libmill_la-poller.lo
  CC       libmill_la-slist.lo
  CC       libmill_la-stack.lo
  CC       libmill_la-tcp.lo
  CC       libmill_la-timer.lo
  CC       libmill_la-udp.lo
  CC       libmill_la-unix.lo
  CC       dns/libmill_la-dns.lo
  CC       libmill_la-file.lo
  CCLD     libmill.la
  CC       perf/go.o
  CCLD     perf/go
  CC       perf/ctxswitch.o
  CCLD     perf/ctxswitch
  CC       perf/chan.o
  CCLD     perf/chan
  CC       perf/chs.o
  CCLD     perf/chs
  CC       perf/chr.o
  CCLD     perf/chr
  CC       perf/whispers.o
  CCLD     perf/whispers
  CC       perf/c10k.o
  CCLD     perf/c10k
  CC       tutorial/step1.o
  CCLD     tutorial/step1
  CC       tutorial/step2.o
  CCLD     tutorial/step2
  CC       tutorial/step3.o
  CCLD     tutorial/step3
  CC       tutorial/step4.o
  CCLD     tutorial/step4
  CC       tutorial/step5.o
  CCLD     tutorial/step5
  CC       tutorial/step6.o
  CCLD     tutorial/step6
  CC       tutorial/step7.o
  CCLD     tutorial/step7
  CCLD     tutorial/step8
/usr/bin/ld: i386:x86-64 architecture of input file `tutorial/step8.o' is incompatible with i386 output
/usr/bin/ld: tutorial/step8.o: file class ELFCLASS64 incompatible with ELFCLASS32
/usr/bin/ld: final link failed: File in wrong format
collect2: error: ld returned 1 exit status
make: *** [tutorial/step8] Error 1

**Comment by puxxustc** [comment]
You didn't setup your compile toolechain well.
