### ISSUE TITLE
linux 64 and macos

### ISSUE THREAD

**Issue by tonyshaoxu** [puxxustc/muon#14]
I downloaded the pre-build for Linux_x86_64 and used it on Centos 7 as server and on Ubuntu 16.04 as client, also installed it on mac via homebrew as client as well.
but finally I did not make it work on linux or mac. Please take a look at below log and advise.

==========server.conf=======================================

user=nobody

mode=server

server=0.0.0.0

port=2000

key=XXXXXXXXXXXXXXXXXXXXXXX

tunif=tun1

mtu=1400

address=10.0.0.0/31

nat=no

delay=5

duplicate=0

==========client.conf=======================================

user=root

mode=client

server=xxxxxxxx

port=2000

key=XXXXXXXXXXXXXXXXXXXXXXX

tunif=tun1

mtu=1400

address=10.0.0.1/31

peer=10.0.0.0

route=yes

delay=5

duplicate=0

==============================================================================

Ping server on ubuntu
PING 10.0.0.0 (10.0.0.0) 56(84) bytes of data.
64 bytes from 10.0.0.0: icmp_seq=2 ttl=64 time=282 ms
64 bytes from 10.0.0.0: icmp_seq=3 ttl=64 time=275 ms
64 bytes from 10.0.0.0: icmp_seq=4 ttl=64 time=268 ms
64 bytes from 10.0.0.0: icmp_seq=7 ttl=64 time=282 ms
64 bytes from 10.0.0.0: icmp_seq=9 ttl=64 time=302 ms
64 bytes from 10.0.0.0: icmp_seq=10 ttl=64 time=287 ms
64 bytes from 10.0.0.0: icmp_seq=13 ttl=64 time=301 ms
64 bytes from 10.0.0.0: icmp_seq=15 ttl=64 time=297 ms
64 bytes from 10.0.0.0: icmp_seq=17 ttl=64 time=303 ms
64 bytes from 10.0.0.0: icmp_seq=19 ttl=64 time=312 ms
64 bytes from 10.0.0.0: icmp_seq=22 ttl=64 time=297 ms
^C
--- 10.0.0.0 ping statistics ---
25 packets transmitted, 11 received, 56% packet loss, time 24257ms
rtt min/avg/max/mdev = 268.422/291.950/312.578/12.903 ms

==============================================================================

Ping server on mac 
PING 10.0.0.0: 56 data bytes
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

==============================================================================

**Comment by tonyshaoxu** [comment]
i figured it out, i have to set nat=yes

**Comment by tonyshaoxu** [comment]
client.conf on Mac

user=root
mode=client
server=xxxxx
port=2000
key=xxxxxxxxxxxxxxxxx
tunif=utun2
mtu=1400
address=10.0.0.2/31
peer=10.0.0.0
route=yes
delay=5

I tested several times, every time the log showed the program was running properly, but no data sent or received via utun2, tried to ping server and got 
PING 10.0.0.0: 56 data bytes
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4

the version of muon installed on Mac is 0.4.1
macOS Sierra 10.12.5

Please let know if you need more information.

**Comment by puxxustc** [comment]
The address of each side should be in the same subnet. If you are not familiar with network config in Linux, maybe this program is not suitable for you .

**Comment by tonyshaoxu** [comment]
Actually it is now working on linux, but on Mac it is a mess.

**Comment by tonyshaoxu** [comment]
Obviously you did not read my post carefully. Anyway thanks.

**Comment by puxxustc** [comment]
1. One server for one client
2. 10.0.0.0 is not in subnet 10.0.0.2/31
