### ISSUE TITLE
muon static file X86

### ISSUE THREAD

**Issue by gvsurenderreddy** [puxxustc/muon#18]
Hello sir do you have binary for X86 please when i try to make i get error 

/muon# make
make  all-recursive
make[1]: Entering directory `/root/muon'
Making all in src
make[2]: Entering directory `/root/muon/src'
depbase=`echo conf.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT conf.o -MD -MP -MF $depbase.Tpo -c -o conf.o conf.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo compress.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT compress.o -MD -MP -MF $depbase.Tpo -c -o compress.o compress.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo crypto.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT crypto.o -MD -MP -MF $depbase.Tpo -c -o crypto.o crypto.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo encapsulate.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT encapsulate.o -MD -MP -MF $depbase.Tpo -c -o encapsulate.o encapsulate.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo log.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT log.o -MD -MP -MF $depbase.Tpo -c -o log.o log.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo tunif.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT tunif.o -MD -MP -MF $depbase.Tpo -c -o tunif.o tunif.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo utils.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT utils.o -MD -MP -MF $depbase.Tpo -c -o utils.o utils.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo vpn.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT vpn.o -MD -MP -MF $depbase.Tpo -c -o vpn.o vpn.c &&\
	mv -f $depbase.Tpo $depbase.Po
vpn.c: In function ‘client_hop’:
vpn.c:260:18: warning: variable ‘i’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
         for (int i = 0; i < ctx.path_count; i++)
                  ^
vpn.c: In function ‘vpn_run’:
vpn.c:157:18: warning: variable ‘i’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
         for (int i = 0; i < ctx.path_count; i++)
                  ^
vpn.c:159:22: warning: variable ‘j’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
             for (int j = 0; j <= ctx.paths[i].port_range; j++)
                      ^
depbase=`echo totp.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT totp.o -MD -MP -MF $depbase.Tpo -c -o totp.o totp.c &&\
	mv -f $depbase.Tpo $depbase.Po
depbase=`echo main.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
	gcc -std=gnu99 -DHAVE_CONFIG_H -I. -I..   -I/root/muon/lz4/lib -I/root/muon/libmill -I/root/muon/libsodium/src/libsodium/include -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1 -MT main.o -MD -MP -MF $depbase.Tpo -c -o main.o main.c &&\
	mv -f $depbase.Tpo $depbase.Po
gcc -std=gnu99 -O3 -pipe -W -Wall -fno-strict-aliasing -DAC_LITTLE_ENDIAN=1  -L/root/muon/lz4/lib -L/root/muon/libmill/.libs -L/root/muon/libsodium/src/libsodium/.libs -static -o muon conf.o compress.o crypto.o encapsulate.o log.o tunif.o utils.o vpn.o totp.o main.o -llz4 -lmill -lsodium
utils.o: In function `runas':
utils.c:(.text+0x10): warning: Using 'getpwnam' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/root/muon/libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-core.o): In function `sodium_crit_enter':
/root/libsodium/src/libsodium/sodium/core.c:133: undefined reference to `pthread_mutex_lock'
/root/muon/libsodium/src/libsodium/.libs/libsodium.a(libsodium_la-core.o): In function `sodium_crit_leave':
/root/libsodium/src/libsodium/sodium/core.c:153: undefined reference to `pthread_mutex_unlock'
/root/libsodium/src/libsodium/sodium/core.c:153: undefined reference to `pthread_mutex_unlock'
/root/libsodium/src/libsodium/sodium/core.c:153: undefined reference to `pthread_mutex_unlock'
/root/libsodium/src/libsodium/sodium/core.c:153: undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__register_frame_info_bases':
(.text+0x173e): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__register_frame_info_bases':
(.text+0x1755): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__register_frame_info_table_bases':
(.text+0x1855): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__register_frame_info_table_bases':
(.text+0x186c): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__deregister_frame_info_bases':
(.text+0x193d): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `__deregister_frame_info_bases':
(.text+0x19af): undefined reference to `pthread_mutex_unlock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `_Unwind_Find_FDE':
(.text+0x1a7a): undefined reference to `pthread_mutex_lock'
/usr/lib/gcc/i686-linux-gnu/4.8/libgcc_eh.a(unwind-dw2-fde-dip.o): In function `_Unwind_Find_FDE':
(.text+0x1ac9): undefined reference to `pthread_mutex_unlock'
collect2: error: ld returned 1 exit status
make[2]: *** [muon] Error 1
make[2]: Leaving directory `/root/muon/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/muon'
make: *** [all] Error 2

**Comment by puxxustc** [comment]
DO NOT SPAM.
